-- Anonymize/soften disease_pages.patient_story quotes that contain exact
-- lab values or percentages, per the 2026-09-11 build spec's legal rule:
-- no named-patient testimonials with exact numbers/lab values/percentages.

update disease_pages set patient_story = '{"quote":"I had vitiligo spreading on my face and both hands for nearly 9 years. I had visited three dermatologists and two other homeopaths before coming to Dr Yadav. Nothing had stopped the spread. Within 4 months of starting treatment at Yadav Homeo Clinic, I noticed that no new patches were forming — for the first time in years. By the 8th month I could see small brown dots forming inside the patches on my cheek. By 14 months the facial patches have shown substantial repigmentation. My hands are showing slower progress but are improving. I wish I had come here first. Individual results vary.","attribution":"Patient, Delhi — Vitiligo, 14 months of treatment"}'::jsonb
where slug = 'skin-diseases';

update disease_pages set patient_story = '{"quote":"My father''s kidney health had declined significantly and our nephrologist raised serious concerns about the road ahead. My aunt suggested Dr Yadav. We were not hopeful but we had nothing to lose. We started treatment soon after, alongside his nephrologist''s ongoing care. I shared reports every 6 weeks as instructed. Over the following 6 months, his kidney function showed meaningful, sustained improvement. He is eating, he is active. His nephrologist continues to monitor him closely. We thank God every day. Individual results vary.","attribution":"Family member, Jaipur — CKD patient, meaningful improvement in kidney function over 6 months","note":"This patient''s outcome may not be typical. Results vary based on kidney function at treatment start, underlying cause, and compliance with nephrologist''s care."}'::jsonb
where slug = 'renal-diseases';

update disease_pages set patient_story = '{"quote":"My semen analysis had shown a very low sperm count and low motility. My wife and I had been trying to conceive for 3 years. IVF with ICSI was recommended. I started constitutional treatment with Dr Yadav. Over the following months, my sperm count and motility both showed substantial improvement on repeat testing. We conceived naturally in the 8th month of treatment. We have a son now. I still find it difficult to believe. Individual results vary.","attribution":"Patient, Rajasthan — Severe oligospermia, natural conception in month 8 of treatment"}'::jsonb
where slug = 'mens-health';

update disease_pages set patient_story = '{"quote":"I had IBS for 11 years. Alternating constipation and diarrhoea, severe bloating after every meal, and cramping that affected my work and social life. I had tried every gastroenterologist''s recommendation — fibre, probiotics, antispasmodics. Nothing lasted. After 4 months of constitutional treatment with Dr Yadav, my stools normalised for the first time in over a decade. The bloating is far better than before. I still have occasional off days but they are nothing like before. My life has genuinely changed. Individual results vary.","attribution":"Patient, Jaipur — IBS for 11 years, significant improvement at 4 months"}'::jsonb
where slug = 'digestive-diseases';

update disease_pages set patient_story = '{"quote":"I was diagnosed with Hashimoto''s thyroiditis 5 years ago and put on levothyroxine. My thyroid antibody levels and TSH were both significantly elevated. I started constitutional homeopathic treatment with Dr Yadav alongside my thyroxine. After 8 months, my antibody levels and TSH had both improved substantially on repeat testing. My endocrinologist reduced my thyroxine dose. I feel better than I have in years — the fatigue and hair loss that persisted even on thyroxine have significantly improved. We are continuing treatment. Individual results vary.","attribution":"Patient, Jaipur — Hashimoto''s thyroiditis, significant reduction in antibody levels over 8 months"}'::jsonb
where slug = 'hormonal-diseases';
